version: '3.9'
services:
  nifi:
    image: apache/nifi:1.13.2
    environment: 
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_HTTP_HOST: 0.0.0.0
    ports: 
      - 8080:8080
    volumes: 
      - ./data:/data
      - ./driver:/driver
      - ./extensions:/opt/nifi/nifi-current/extensions
      # - ./content_repository:/opt/nifi/nifi-current/content_repository
      # - ./database_repository:/opt/nifi/nifi-current/database_repository
      # - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      # - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hyman
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: hyman@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8081:80"